## Overview

In this PA, you will will be creating and manipulating basic objects to uncover a top secret message.

### Hint 1

As you work through this PA, you will encounter some code that does not work as you want it to.  Don't despair!  Errors (when R is unable to run your code) and bugs (when the code doesn't do what you hoped) are a natural part of coding.  Even the best of the best deal with these problems regularly - learning to track down the issue is a skill that you can learn and practice.

Google is your friend!  If an error is confusing, copy it into Google and see what other people are saying.  If you don't know how to do something, search for it.

### Hint 2

Just because there is no error message doesn't mean everything went smoothly.  You should be regularly printing out your objects, to see they contain the information and format that you expect.

For example, if you have an object named `my_thing`, you might first want to simply look at the object by typing its name.

However, you might also want to make sure it is the right **object type** and/or the right **object structure**.


In [58]:
type(my_thing)
len(my_thing)

NameError: name 'my_thing' is not defined

## Part One: Setup

Each of the following code chunks will cause an error and/or do the desired task incorrectly.  Find the mistake, and correct it to complete the intended action.




1. Create lists containing the upper case letters, lower case letters, and some punctuation marks.


In [59]:
lower_case = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]

upper_case = ["A", "B", "C", "D", "E", "F", "G", "H" "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

punctuation = [".", ",", "!", "?", "'", '"', "(", ")", " ", "-", ";", ":"]

2. Make one long list containing all the symbols.  Find the length of this list.


In [60]:
all_symbols = lower_case + upper_case + punctuation

len(all_symbols)

63

3. Repeat the previous steps, but instead of using *list* type objects, use **numpy arrays**.  Don't forget to **import** the numpy library!


In [61]:
import numpy as np


lower_case = np.array(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"])

upper_case = np.array(["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"])

punctuation = np.array([".", ",", "!", "?", "'", "\"", "(", ")", " ", "-", ";", ":"])



## Use np.concatenate to combine into long array
all_symbols = np.concatenate((lower_case, upper_case, punctuation))

4. Make a **pandas data frame**, with one column called "Symbol" containing the `all_symbols` array.


In [62]:
import pandas as pd

symbols_df = pd.DataFrame(all_symbols)
symbols_df = symbols_df.rename(columns = {0: "Symbol"})
symbols_df


Symbol
0       a
1       b
2       c
3       d
4       e
..    ...
59      )
60       
61      -
62      ;
63      :

[64 rows x 1 columns]

## Part Two: Decoding the secret message.


In [84]:
top_secret = pd.read_csv("https://www.dropbox.com/s/k72h1zewk4gtqep/PA_Secret_Code?dl=1", header=None)
top_secret = top_secret[0].to_numpy()

### Hint

Recall that basic math operations are **vectorized**.  This means you don't have to repeat the process for each item in a list; you can apply the math to the whole thing at once.

### Instructions

By altering this top secret set of numbers, you will be able to create a message.  Write your own code to complete the steps below.

1. Add 14 to every number.
2. Multiply every number by 18, then subtract 257.
3. Exponentiate every number.  (That is, do e^[number].  You may have to Google how to do this!)
4. Square every number.

**Checkpoint:** Headquarters has informed you that at this stage of decoding, there should be 352 numbers in the secret message that are below 17.  Write code to check if this is true for your data.


5. Turn your one-dimensional array of numbers into a two-dimensional array (matrix) with 5 columns.
6. Separately from your top secret numbers, create an array of all the even numbers between 1 and 382. Name it "evens". That is, "evens" should contain 2, 4, 6, 8 ..., 382.
7. Subtract the "evens" vector from the first column of your secret message matrix.
8. Subtract 100 from all numbers in the 18-24th rows of the 3rd column.
9. Multiply all numbers in the 4th and 5th column by 2.
10. Turn your matrix back into a one dimensional array.


**Checkpoint:** Headquarters has informed you that at this stage of decoding, all numbers in indices 500 and beyond are below 100.  Write code to check if your numbers fulfill this requirement.

11. Take the square root of all numbers in indices 38 to 465.
12. Round all numbers to the nearest whole number.
13. Replace all instances of the number 39 with 20.

**Checkpoint:** Headquarters has informed you that your final message should have 344 even numbers.  Write code to check if your numbers fulfill this requirement.

## Part 3: The secret message!

Run the following to discover the final message!  Google the first line of this message, if you do not recognize it, to see what it is.


In [85]:
top_secret = top_secret + 14
top_secret = top_secret*18
top_secret = top_secret - 257
top_secret = np.exp(top_secret)
top_secret = top_secret**2

In [86]:
len(top_secret[top_secret<17])

352

In [87]:
top_secret = top_secret.reshape(5,-1).T
evens = np.arange(2,384,2)
top_secret[:,0] = top_secret[:,0]-evens
top_secret[17:24, 2] = top_secret[17:24,2] - 100
top_secret[:,3:5] = top_secret[:,3:5]*2
top_secret = top_secret.T.flatten()

In [88]:
sum(top_secret[500:955]>=100)

0

In [89]:
#first_column = top_secret[0:len(top_secret)//5]
#second_column = top_secret[len(top_secret)//5: 2*(len(top_secret)//5)]
#third_column = top_secret[(2*len(top_secret)//5): 3*(len(top_secret)//5)]
#fourth_column = top_secret[(3*len(top_secret)//5): 4*(len(top_secret)//5)]
#fifth_column = top_secret[(4*len(top_secret)//5): 5*(len(top_secret)//5)]

#top_secret = np.array([first_column,second_column,third_column,fourth_column,fifth_column])

In [90]:
#evens = np.arange(2,384,2)

In [91]:
#first_column = first_column-evens
#third_column[17:24] = third_column[17:24]-100
#fourth_column = fourth_column*2
#fifth_column = fifth_column*2
#top_secret = np.concatenate((first_column,second_column,third_column,fourth_column,fifth_column))

In [92]:
#top_secret[0] = top_secret[0] - evens

In [93]:
#top_secret[2,17:24] = top_secret[2,17:24]-100

In [94]:
#top_secret[3] = top_secret[3]*2
#top_secret[4] = top_secret[4]*2

In [95]:
#top_secret = np.concatenate((top_secret[0], top_secret[1], top_secret[2], top_secret[3], top_secret[4]))

In [96]:
top_secret

array([5.700e+01, 4.600e+01, 2.300e+01, 1.000e+00, 1.900e+01, 6.100e+01,
       2.000e+00, 1.800e+01, 9.000e+00, 1.200e+01, 1.200e+01, 9.000e+00,
       7.000e+00, 5.400e+01, 6.100e+01, 1.000e+00, 1.400e+01, 4.000e+00,
       6.100e+01, 3.900e+01, 8.000e+00, 5.000e+00, 6.100e+01, 1.900e+01,
       1.200e+01, 9.000e+00, 3.900e+01, 8.000e+00, 2.500e+01, 6.100e+01,
       3.900e+01, 1.500e+01, 2.200e+01, 5.000e+00, 1.900e+01, 6.100e+01,
       6.100e+01, 3.721e+03, 9.000e+02, 8.100e+01, 1.600e+01, 3.721e+03,
       4.900e+01, 6.250e+02, 3.240e+02, 2.500e+01, 3.721e+03, 1.000e+00,
       1.960e+02, 1.600e+01, 3.721e+03, 4.900e+01, 8.100e+01, 1.690e+02,
       4.000e+00, 1.440e+02, 2.500e+01, 3.721e+03, 8.100e+01, 1.960e+02,
       3.721e+03, 1.521e+03, 6.400e+01, 2.500e+01, 3.721e+03, 5.290e+02,
       1.000e+00, 4.000e+00, 2.500e+01, 4.096e+03, 3.721e+03, 7.290e+02,
       1.440e+02, 1.440e+02, 3.721e+03, 1.690e+02, 8.100e+01, 1.690e+02,
       3.610e+02, 6.250e+02, 3.721e+03, 5.290e+02, 

In [97]:
#Take the square root of all numbers in indices 38 to 465.
#Round all numbers to the nearest whole number.
#Replace all instances of the number 39 with 20.

top_secret[37:465] = top_secret[37:465]**(1/2)
top_secret


array([57., 46., 23.,  1., 19., 61.,  2., 18.,  9., 12., 12.,  9.,  7.,
       54., 61.,  1., 14.,  4., 61., 39.,  8.,  5., 61., 19., 12.,  9.,
       39.,  8., 25., 61., 39., 15., 22.,  5., 19., 61., 61., 61., 30.,
        9.,  4., 61.,  7., 25., 18.,  5., 61.,  1., 14.,  4., 61.,  7.,
        9., 13.,  2., 12.,  5., 61.,  9., 14., 61., 39.,  8.,  5., 61.,
       23.,  1.,  2.,  5., 64., 61., 27., 12., 12., 61., 13.,  9., 13.,
       19., 25., 61., 23.,  5., 18.,  5., 61., 39.,  8.,  5., 61.,  2.,
       15., 18., 15.,  7., 15., 22.,  5., 19., 54., 61., 61., 61., 27.,
       14.,  4., 61., 39.,  8.,  5., 61., 13., 15., 13.,  5., 61., 18.,
        1., 39.,  8., 19., 61., 15., 21., 39.,  7., 18.,  1.,  2.,  5.,
       53., 61., 58., 28.,  5., 23.,  1., 18.,  5., 61., 39.,  8.,  5.,
       61., 36.,  1.,  2.,  2.,  5., 18., 23., 15.,  3., 11., 54., 61.,
       13., 25., 61., 19., 15., 14., 55., 61., 61., 61., 46.,  8.,  5.,
       61., 10.,  1., 23., 19., 61., 39.,  8.,  1., 39., 61.,  2

In [98]:
top_secret = np.round(top_secret)

In [99]:
top_secret[top_secret == 39] = 20

In [100]:
len(top_secret[top_secret%2 == 0])

344

In [101]:
len(top_secret)

955

In [102]:
top_secret=top_secret-1

In [103]:
top_secret

array([56., 45., 22.,  0., 18., 60.,  1., 17.,  8., 11., 11.,  8.,  6.,
       53., 60.,  0., 13.,  3., 60., 19.,  7.,  4., 60., 18., 11.,  8.,
       19.,  7., 24., 60., 19., 14., 21.,  4., 18., 60., 60., 60., 29.,
        8.,  3., 60.,  6., 24., 17.,  4., 60.,  0., 13.,  3., 60.,  6.,
        8., 12.,  1., 11.,  4., 60.,  8., 13., 60., 19.,  7.,  4., 60.,
       22.,  0.,  1.,  4., 63., 60., 26., 11., 11., 60., 12.,  8., 12.,
       18., 24., 60., 22.,  4., 17.,  4., 60., 19.,  7.,  4., 60.,  1.,
       14., 17., 14.,  6., 14., 21.,  4., 18., 53., 60., 60., 60., 26.,
       13.,  3., 60., 19.,  7.,  4., 60., 12., 14., 12.,  4., 60., 17.,
        0., 19.,  7., 18., 60., 14., 20., 19.,  6., 17.,  0.,  1.,  4.,
       52., 60., 57., 27.,  4., 22.,  0., 17.,  4., 60., 19.,  7.,  4.,
       60., 35.,  0.,  1.,  1.,  4., 17., 22., 14.,  2., 10., 53., 60.,
       12., 24., 60., 18., 14., 13., 54., 60., 60., 60., 45.,  7.,  4.,
       60.,  9.,  0., 22., 18., 60., 19.,  7.,  0., 19., 60.,  1

In [104]:
''.join(map(str, symbols_df.loc[top_secret]['Symbol']))

'\'Twas brillig, and the slithy toves   Did gyre and gimble in the wabe: All mimsy were the borogoves,   And the mome raths outgrabe. "Beware the Jabberwock, my son!   The jaws that bite, the claws that catch! Beware the Jubjub bird, and shun   The frumious Bandersnatch!" He took his vorpal sword in hand;   Long time the manxome foe he sought- So rested he by the Tumtum tree   And stood awhile in thought. And, as in uffish thought he stood,   The Jabberwock, with eyes of flame, Came whiffling through the tulgey wood,   And burbled as it came! One, two! One, two! And through and through   The vorpal blade went snicker-snack! He left it dead, and with its head   He went galumphing back. "And hast thou slain the Jabberwock?   Come to my arms, my beamish boy! O frabjous day! Callooh! Callay!"   He chortled in his joy. \'Twas brillig, and the slithy toves   Did gyre and gimble in the wabe: All mimsy were the borogoves,   And the mome raths outgrabe.'

In [122]:
top_secret

AttributeError: 'numpy.ndarray' object has no attribute 'index'

64